### ISSUE TITLE
Error: --stages-storage=ADDRESS param required

### ISSUE THREAD

**Issue by NLaws** [werf/werf-guides#47]
Working through the tutorial https://werf.io/guides/nodejs/100_basic/10_build.html one gets 
```
Error: --stages-storage=ADDRESS param required
```
from `werf build` and `werf run --docker-options="--rm -p 3000:3000" -- node /app/app.js`

By searching through the project files it seems that the tutorial should instruct users to:
```werf build --stages-storage :local```
and 
```
werf run --docker-options="--rm -p 3000:3000" --stages-storage=:local -- node /app/app.js
```

**Comment by z9r5** [comment]
Hi, @NLaws!

Please check  `werf version`. It seems you are using werf 1.1 instead of 1.2. 

The guide implies using werf 1.2.x.

Regards!

**Comment by NLaws** [comment]
Yes that was the problem thank you @z9r5!
