### ISSUE TITLE
Bug: Some scripts were lost.

### ISSUE THREAD

**Issue by NikitaIT** [werf/werf-guides#86]
## Reproduction:
1. Go to: [Разворачиваем приложение на Node.js в среде Kubernetes](https://ru.werf.io/guides/nodejs/200_real_apps/50_files.html)
2. Click on btn `Показать, что уже готово`.
3. Nothing happens.

## In Code
Removal of ` {% asset details.js %}` resulted in:

![Btn not clickable](https://user-images.githubusercontent.com/16810067/115150688-cad68a00-a069-11eb-8050-3fe577bf94ca.png)

This affects all pages.
https://github.com/werf/werf-guides/blob/c32cfe34bceabe9c6537755219146cb32f08c336/ru.werf.io/guides/_layouts/wip.html#L18

The changes that led to this: https://github.com/werf/werf-guides/commit/64d07386d1010f92cd2bdcf75ec71a8711070545#r49666757

**Comment by z9r5** [comment]
@NikitaIT Thank you for the issue!
